<?php

namespace AppBundle\Repository;

/**
 * visitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visitasRepository extends \Doctrine\ORM\EntityRepository
{
}
